spring:
  jpa:
    org:
      hibernate:
        envers:
          audit_table_suffix: _history
          revision_field_name: rev_id
          store_data_at_delete: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:4306/test
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

decorator:
  datasource:
    p6spy:
      enable-logging: off
      multiline: true